version: '3.9'

services:
  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    ports:
      - "8443:443"
    volumes:
      - ../secrets:/etc/nginx/ssl
      - data_wordpress:/var/www/html
      - ./requirements/bonus/portfolio:/var/www/html/portfolio
    networks:
      - docker-network 

  db:
    container_name: mariadb
    restart: always
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    env_file: .env
    volumes:
      - data_db:/var/lib/mysql
    networks:
      - docker-network
    secrets:
      - db_root_password
      - db_password
  
  wordpress:
    container_name: wordpress
    restart: always
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    env_file: .env
    networks:
      - docker-network 
    volumes:
      - data_wordpress:/var/www/html
    depends_on:
      - db
      - redis
    secrets:
      - admin_password
      - db_password
      - user_password
      - redis_password
  
  redis:
    container_name: redis
    restart: always
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
    image: redis
    networks:
      - docker-network
    secrets:
      - redis_password

  ftp:
    container_name: vsftp
    restart: always
    build:
      context: ./requirements/bonus/ftp
      dockerfile: Dockerfile
    image: ftp
    ports:
      - 21:21
    networks:
      - docker-network
    volumes:
      - data_wordpress:/var/www/html

volumes:
  data_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/dinandrianom/test/data/db
  data_wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/dinandrianom/test/data/wordpress


networks:
  docker-network:
    driver : bridge

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  admin_password:
    file: ../secrets/admin_password.txt
  user_password:
    file: ../secrets/user_password.txt
  redis_password:
    file: ../secrets/redis_password.txt
