version: '3'

services:
  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    ports:
      - "443:443"
    volumes:
      - ../secrets/certificate:/etc/nginx/ssl
      - ./requirements/bonus/portfolio:/var/www/html/portfolio
      - data_wordpress:/var/www/html
      - data_phpmyadmin:/var/www/html/phpmyadmin
    networks:
      - docker-network 

  mariadb:
    container_name: mariadb
    restart: always
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    env_file: .env
    volumes:
      - data_mariadb:/var/lib/mysql
    networks:
      - docker-network
    secrets:
      - db_root_password
      - db_password
  
  wordpress:
    container_name: wordpress
    restart: always
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    env_file: .env
    networks:
      - docker-network 
    volumes:
      - data_wordpress:/var/www/html
    depends_on:
      - mariadb
      - redis
    secrets:
      - admin_password
      - db_password
      - user_password
      - redis_password
  
  redis:
    container_name: redis
    restart: always
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
    image: redis
    networks:
      - docker-network
    secrets:
      - redis_password

  vsftpd:
    container_name: vsftpd
    restart: always
    build:
      context: ./requirements/bonus/ftp
      dockerfile: Dockerfile
    image: vsftpd
    env_file: .env
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    networks:
      - docker-network
    volumes:
      - data_wordpress:/home/ftpuser/ftp/files
    secrets:
      - ftp_password

  adminer:
    container_name: adminer
    restart: always
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    image: adminer
    networks:
      - docker-network

  phpmyadmin:
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mariadb
    build:
      context: ./requirements/bonus/phpmyadmin
      dockerfile: Dockerfile
    volumes:
      - data_phpmyadmin:/var/www/html/phpmyadmin
    image: phpmyadmin
    networks:
      - docker-network

volumes:
  data_mariadb:
    name: data_mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/tolrandr/data/mariadb
  data_wordpress:
    name: data_wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/tolrandr/data/wordpress
  data_phpmyadmin:
    name: data_phpmyadmin
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/tolrandr/data/phpmyadmin

networks:
  docker-network:
    driver : bridge

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  admin_password:
    file: ../secrets/admin_password.txt
  user_password:
    file: ../secrets/user_password.txt
  redis_password:
    file: ../secrets/redis_password.txt
  ftp_password:
    file: ../secrets/ftp_password.txt